#use m for minute
time_before_use: 2m

messages:
  prefix: "&7[&c&lEnderPearlCooldown&7] "
  second: "second"
  seconds: "seconds"
  minute: "minute"
  minutes: "minutes"
  #use {0} for the seconds and minutes
  cancel_message: "You must wait {0} before use another enderpearl !"
  no_permission: "You haven't the permission!"